### ISSUE TITLE
Grunt and grunt deploy building incomplete jquery.SPServices.js

### ISSUE THREAD

**Issue by alandtse** [sympmarc/SPServices#22]
Following the readme instructions to build (i.e. using grunt or grunt deploy), the output under /build appears truncated and is missing the functions (e.g., SPRequireUnique, etc.)

For comparison, jquery.SPServices.js in /dist is 4,575 lines while with a clean git clone /build creates one that is 2,965 lines.  It looks like grunt is not traversing into /src/utils and /src/value-add to include those files.

Does Gruntfile.js or the readme need to be updated?

I'm building this on a fresh vagrant box built from https://atlas.hashicorp.com/lazygray/boxes/heroku-cedar-14

**Comment by purtuga** [comment]
I don't have access to a computer now, but it's possible that the deploy task is not copying all src files.  Does a "dist" or "build" create the correct files under /dist ?

Paul
-- sent from mobile

**Comment by purtuga** [comment]
I should have mentioned this: I would not try to use/build the SPServices code base at this time from github MASTER branch, and would stick to an official version released via CodePlex.  This code base is undergoing a major refactoring effort and until that is complete, it may not be stable. 
Paul
-- sent from mobile

**Comment by alandtse** [comment]
I grepped the Gruntfile and it doesn't look like it actually touches /dist.  Got it about the refactoring.  I had some bug fixes/enhancements that I was planning to submit a pull request for but wanted to make sure it didn't break the latest code base.

**Comment by purtuga** [comment]
Ahhhh. Ok.  Good workflow.  Always make sure you known what you are starting with.   :-)
I think the issue is that although Marc has broken out several methods into AMD, they are not yet all linked up to be included in the final compiled file. 

Sorry I can't look any closer right now.  I don't have access to a computer.  But will, as soon as I can. 

Paul
-- sent from mobile

**Comment by purtuga** [comment]
@alandtse could you try again? 
The build issue has been addressed.  But note that not all functionality of the prior SPServices library is there yet.

**Comment by sympmarc** [comment]
@alandtse Sorry I never replied to you here. In the last few weeks, I've been building the build up from core. If you see a module in /src, then it's currently included. I've got all the other modules segregated out into a private /todo directory, and I'm adding them in one by one.

If you have a suggested fix, base it on 2014.02 and I can retrofit it. Thanks!

**Comment by sympmarc** [comment]
I think this is ancient history at this point. Create a new issue if it's still outstanding...
