### ISSUE TITLE
jquery.SPServices.d.ts is incomplete

### ISSUE THREAD

**Issue by kbatman37** [sympmarc/SPServices#23]
The TypeScript definition file found in `jquery.SPServices.d.ts` appears to be incomplete and defines only `SPCascadeDropdowns`.

**Comment by sympmarc** [comment]
That's correct. @johnnliu gave it a start. Feel free to build upon that and contribute back.

**Comment by johnnliu** [comment]
I also defined the default $().SPServices() method, which is arguably the big method that everyone uses...  

I agree it's incomplete, for example, I'd like to add SPXmlToJson etc.

**Comment by lirichard** [comment]
Bit late to the party, but I worked on fleshing out the TypeScript definitions quite a bit; the results so far are on my fork of this repo, branch `ts-definitions` ([link to the file](https://github.com/lirichard/SPServices/blob/ts-definitions/src/jquery.SPServices.d.ts)). I'm pretty new to TS as well as SPServices, so a grain or several of salt is probably appropriate. Would love to get this pulled and updated at some point though.

More changes to come, but I would appreciate if some folks more experienced with the library could take a look and advise on anything that looks terribly wrong!

**Comment by sympmarc** [comment]
@lirichard Sorry for the delay in looking at this. @juliemturner and I are taking a look and we'll probably add your changes soon. If you've done any more and can submit a pull request, even better!

**Comment by juliemturner** [comment]
@lirichard if you want to submit a pull request I'll look at the changes you made, pretty hard to do that comparison in your fork.  Thanks

**Comment by lirichard** [comment]
Created pull request!

**Comment by juliemturner** [comment]
Merge accepted.  Thanks for your hard work on this.
