### ISSUE TITLE
Add displayFormat: "none" to SPDisplayRelatedInfo

### ISSUE THREAD

**Issue by sympmarc** [sympmarc/SPServices#28]
Sometimes you don't even want to see the values; you just want to do something with them in the completefunc.

**Comment by wobba** [comment]
You should also pass the data fetched in as a parameter to completefunc. Something like:

    if (opt.completefunc !== null) {
       opt.completefunc(relatedColumnsXML);
    }

**Comment by sympmarc** [comment]
I made these changes in [commit ac7824090a1ebed105c770c187115cb9b605d5fc](https://github.com/sympmarc/SPServices/commit/ac7824090a1ebed105c770c187115cb9b605d5fc)

**Comment by Gabreezy03** [comment]
$().SPServices.SPDisplayRelatedInfo({
  columnName: "Applicable finding",
  relatedList: "Findings",
  relatedColumns: ["PzlInspector", "PzlSiteName", "PzlDepartment"],
  displayFormat: "none",
  matchOnId: true,
  completefunc: function(data) {
     # if( $('select[id^="PzlFindingLookup"]').val() != 0) {
        setFormValues(data);
      }
  }
});
