### ISSUE TITLE
Weburl

### ISSUE THREAD

**Issue by dinnouti** [sympmarc/SPServices#54]
I am running SPServices' GetListItems from a subsite (https://something.sharepoint.com/sites/intranet/op1/) querying a document library in the root. This is my SPServices code.

```
$().SPServices(
{
    webUrl         : 'https://something.sharepoint.com/sites/intranet/',
    operation      : "GetListItems",
    async          : true,
    listName       : 'Documents',
    CAMLViewFields : "<ViewFields><FieldRef Name='Title' /><FieldRef Name='EncodedAbsUrl'/></ViewFields>",
    // CAMLQuery      : camlQuery,
    completefunc   : function (xData, Status)
        {
            console.log('doclib_getListItems [xData]', xData);
            console.log('doclib_getListItems [Status]', Status);
        }
});
```

However I am getting an error "POST https://something.sharepoint.com/sites/intranet/op1/_vti_bin/Lists.asmx 500 (Internal Server Error)". I think it is trying to find the "Documents" list in the subsite but not in the site indicated by the webUrl. Is there a way to force SPServices to query https://something.sharepoint.com/sites/intranet/_vti_bin/Lists.asmx ?

Please note the opt1 in the subsite url.

thanks!

**Comment by sympmarc** [comment]
Rather than `webUrl         : 'https://something.sharepoint.com/sites/intranet/'`, you should be providing a relative path, like this:

`webUrl         : '/sites/intranet/'`

**Comment by dinnouti** [comment]
thanks for quick reply. I changed the code like you recommended:
```
$().SPServices(
{
    webUrl         : '/sites/intranet/',
    operation      : "GetListItems",
    async          : true,
    listName       : 'Documents',
    CAMLViewFields : "<ViewFields><FieldRef Name='Title' /><FieldRef Name='EncodedAbsUrl'/></ViewFields>",
    // CAMLQuery      : camlQuery,
    completefunc   : function (xData, Status)
        {
            console.log('doclib_getListItems [xData]', xData);
            console.log('doclib_getListItems [Status]', Status);
        }
});
```

The SPServices still wants to query "https://something.sharepoint.com/sites/intranet/op1/_vti_bin/Lists.asmx ", by the way, I am using SharePoint online (O365).

**Comment by sympmarc** [comment]
Doh! Sorry, I missed the obvious thing: you'v'e spelled `webURL` incorrectly.

**Comment by dinnouti** [comment]
thanks!

**Comment by dinnouti** [comment]
this is what happens when one copies code from the internet without double checking. thank you, it was driving me crazy
