### ISSUE TITLE
Can SPCascadedDropdowns have  two parents

### ISSUE THREAD

**Issue by westerdaled** [sympmarc/SPServices#63]
Hi

Firstly, SPServices has been a real lifesaver when compared with having to write acres of plumbing code 
in say SPFx +Office Fabric + ReactJS when building a parent /relationships UI  IMHO  .

Anyway back to my question. I want to use a lookup which works against the relationship list as shown below.   I want select my colour indicator based on the values held in Department and Company .   Can I use CAML to argument the first Parent column?

Title    Department  Company
Green   Sales             Comp1
N/A     Sales            Comp2
Amber   Sales             Comp3

**Comment by sympmarc** [comment]
The trick here would be to store your values in two tables to make them more like relational tables. Then you can call [SPCascadeDropdowns](http://sympmarc.github.io/SPServices/value-added/SPCascadeDropdowns.html) twice, once per relationship.

Without understanding your full data set here, it might be something like:

**Companies**
Title
Comp1
Comp2
Comp3

**Departments**
Title Company Color
Comp1 Sales Comp1 Green
Comp2 Sales Comp2 N/A
Comp3 Sales Comp3 Amber

**Comment by westerdaled** [comment]
Thanks Marc. Since posting, the requirements have changed and I having to replicate the functionality with InfoPath ( for better or worse!) .
