### ISSUE TITLE
Does SPServices cater for filling in fields from another list

### ISSUE THREAD

**Issue by dprivitelli** [sympmarc/SPServices#78]
Hi,

I am currently using SPCascadeDropdowns & SPDisplayRelatedInfo. Is there a way of having something similar to the SPDisplayRelatedInfo which automatically fills in the fields in the current Form from another list based on the selection of the dropdown please?

**Comment by sympmarc** [comment]
@dprivitelli, that's basically what SPDisplayRelated info does: based on the selection in the dropdown, it shows additional information fro the lookup list.

**Comment by dprivitelli** [comment]
Yes I agree. However, I need to get that data and use it to fill other fields, because that data will not be stored in the list but just displayed and I need to store it. Can it be done somehow?

**Comment by sympmarc** [comment]
Your need is a specific requirement that the generic function doesn't provide. It's absolutely possible, but you'll need to write the code for it.
