### ISSUE TITLE
Typo: SPServices.core.js (line 609 - OFFICIALFILE Operations) - too many parameters

### ISSUE THREAD

**Issue by TBemrose** [sympmarc/SPServices#89]
/src/core/SPServices.core.js (line 609) is passing 7 parameters
`609    utils.addToPayload(opt, SOAPEnvelope, ["fileToSubmit"], ["properties"], ["recordRouting"], ["sourceUrl"], ["userName"]);`

/src/core/SPServices.utils.js (line 216) requires 3 parameters, the 3rd being an array
`216    addToPayload: function(opt, SOAPEnvelope, paramArray) {`

**Comment by sympmarc** [comment]
It's been a long time since anyone commented here! This project is basically as-is. I had planned a v2, but never finished it.

It seems like the 5 params should be passed as an array.
